### ISSUE TITLE
Failed to create keypair from CLI config file, falling back to new random keypair

### ISSUE THREAD

**Issue by fuyundian** [solana-labs/example-helloworld#322] opened 2021-09-27 03:20 UTC
Failed to create keypair from CLI config file, falling back to new random keypair

**Comment by yazyyyyy** [comment] 2021-10-06 17:04
I was facing the same error. Just had to update `node.js` to `version 14.x`. It is recommended having version 14 or higher.

**Comment by johnkim-MyFind** [comment] 2022-01-10 02:11
thanks a lot. you saved my life!

**Comment by soynof** [comment] 2022-02-14 20:17
Upgrade versión to 17.x is done.

**Comment by vitaliykononov** [comment] 2022-05-02 15:25
Same issue here, node v is 18

**Comment by cassc** [comment] 2022-08-24 08:44
For me the error is caused by the config path configured in [the yaml](https://github.com/solana-labs/example-helloworld/blob/f332497216f9366f7c2a2bf9e2aa8867ebbf91dc/src/client/utils.ts#L23) which is `~/.config/solana/id.json` does not exist. I have to create one and make sure it has some SOL token.

**Comment by joncinque** [comment] 2023-01-11 13:54
Closing since there's a resolution. In the future, we don't use GitHub for developer support, and encourage you ask your question on the Solana Stack Exchange https://solana.stackexchange.com/ or some other developer support forum.

**Closed by joncinque** 2023-01-11 13:54 UTC
