### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib

### ISSUE THREAD

**Issue by pra-dan** [solana-labs/example-helloworld#236] opened 2021-06-13 10:59 UTC
I am using Solana-CLI version 1.7.1 and rustc version 1.52.1 on a **MacBook Pro M1**. I am trying to run the 'hello-world' example. All step go well except on running

```console
$ solana-test-validator
```

I get
```console
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/prashantdandriyal/.local/share/solana/install/active_release/bin/solana-test-validator
  Reason: image not found
zsh: abort      solana-test-validator
```

[This StackOverflow question](https://stackoverflow.com/questions/59006602/dyld-library-not-loaded-usr-local-opt-openssl-lib-libssl-1-0-0-dylib) suggests downgrading OpenSSL but it seems that Apple has stopped support for OpenSSL and its not possible to downgrade.

The Solana docs do not specify if M1 is compatible with Solana or not.

**Comment by fanatid** [comment] 2021-06-17 05:21
Same as #200

**Comment by yenicelik** [comment] 2021-07-05 13:29
Same issue here

**Comment by steadylearner** [comment] 2021-07-08 10:37
Can't you detect the OS type or arch and use /opt/homebrew/opt/ path instead of /usr/local/opt/ for intel chip?

**Comment by nhamthanh** [comment] 2021-07-09 13:12
@pra-dan 
Just install rosetta 2 and new ur terminal with rosetta. Then install Homebrew, openssl on rosetta terminal.
It will run ok

But you will get new error like this
Ledger location: test-ledger Log: test-ledger/validator.log ⠙ Initializing... zsh: illegal hardware instruction solana-test-validator

**Comment by yenicelik** [comment] 2021-07-09 13:15
Thx a lot! Makes me a hit sad that the dev environments are not fully compatible on m1 yet (but thats expected given its so new…) will stick ethereum for now and come back once it is i guess. Curious how it evolves, solana really looks more interesting in terms if tech and scalability

**Comment by pra-dan** [comment] 2021-07-10 10:56
@nhamthanh You should open a new issue for that. The maintainers will surely look into it ✌️

**Comment by nhamthanh** [comment] 2021-07-10 14:22
> @nhamthanh You should open a new issue for that. The maintainers will surely look into it ✌️

@pra-dan Actually this issue is same with my issue and issue #200 , I think maintainers should make openSSL and solana support structure ARM on M1 in stead of using rosetta. Because It lead too much compile issues.
So no need to open new issue. Just noticed maintainers about their resolve with rosetta is not work.

**Comment by t-nelson** [comment] 2021-07-29 16:56
Closing as duplicate of #200

**Closed** 2021-08-07 23:06 UTC
